<?xml version="1.0" encoding="utf-8"?>
<Project Sdk="Microsoft.NET.Sdk">
  <Import Project="Dalamud.Plugin.Bootstrap.targets" />

  <PropertyGroup>
    <Authors></Authors>
    <Company></Company>
    <Version>0.0.0.1</Version>
    <Description>Bis Translator.</Description>
    <Copyright></Copyright>
    <PackageProjectUrl>https://github.com/Ruukki/BisTranslator</PackageProjectUrl>
    <PackageLicenseExpression>AGPL-3.0-or-later</PackageLicenseExpression>
    <IsPackable>false</IsPackable>
    <TargetFramework>net9.0-windows7.0</TargetFramework>
  </PropertyGroup>

  <ItemGroup>
    <Content Include="..\Data\goat.png">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
      <Visible>false</Visible>
    </Content>
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Buttplug" Version="3.0.1" />
    <PackageReference Include="Buttplug.Client.Connectors.WebsocketConnector" Version="3.0.1" />
    <PackageReference Include="Microsoft.Extensions.DependencyInjection" Version="9.0.2" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Glamourer.Api\Glamourer.Api.csproj" />
    <ProjectReference Include="..\Moodles\Moodles\Moodles.csproj" />
    <ProjectReference Include="..\Penumbra.Api\Penumbra.Api.csproj" />
    <ProjectReference Include="..\WebOverlay\WebOverlay.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Update="DalamudPackager" Version="12.0.0" />
      <Reference Include="InteropGenerator.Runtime">
          <Private>false</Private>
          <HintPath>$(DalamudLibPath)InteropGenerator.Runtime.dll</HintPath>
      </Reference>
  </ItemGroup>

  <ItemGroup>
    <Folder Include="Custom\" />
  </ItemGroup>
    
</Project>
